jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Start API Server
        run: |
          ./start-api-server.sh &  # Ensure your API server start script is correct
          sleep 10  # Give the server time to start

      - name: Run tests
        run: mvn test