name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Start API Server
        run: mvn spring-boot:run &
      - name: Run Tests
        run: mvn test
        env:
          API_URL: http://localhost:8080
          DB_URL: jdbc:postgresql://localhost:5432/testdb
          DB_USER: user
          DB_PASSWORD: password
