name: API Tests with Allure Report

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      api-service:
        image: simbirsoft_sdet_project-service:latest
        ports:
          - 8080:8080
        options: --health-cmd "curl -f http://localhost:8080/health || exit 1" --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify service availability
        run: |
          echo "Waiting for API to start..."
          until curl -s http://localhost:8080/health; do
            sleep 2
          done

      - name: Run tests with Allure
        run: |
          mvn clean test
          mvn allure:report
        env:
          BASE_URL: http://api-service:8080/api

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Generate and publish Allure report
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: target/allure-results
          allure_report: allure-report
          keep_reports: 5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
