name: CI/CD with Allure Report

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      # Step 3: Install Chrome and ChromeDriver
      - name: Install browsers
    run: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
      MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
      CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION")
      wget -N "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      sudo mv chromedriver /usr/local/bin/chromedriver
      sudo chmod +x /usr/local/bin/chromedriver
      google-chrome --version
      chromedriver --version

      # Step 4: Run tests
      - name: Run tests
        run: |
          mvn clean test -B

      # Step 5: Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate target/allure-results -o target/allure-report --clean

      # Step 6: Deploy Allure Report
      - name: Deploy Allure Report
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
          keep_files: true

      # Step 7: Upload Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 3